
services:
  - type: web
    name: twitter-insights-dashboard
    env: python
    pythonVersion: 3.11.0
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run dashboard.py --server.port $PORT --server.address 0.0.0.0
    plan: free
    envVars:
      - key: BEARER_TOKEN
        sync: false
      - key: TWITTER_HANDLES
        sync: false
      - key: COLLECTOR_INTERVAL
        sync: false
